import type * as Preset from "@docusaurus/preset-classic";
import type { Config } from "@docusaurus/types";
import { themes as prismThemes } from "prism-react-renderer";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const GITHUB = "https://github.com/eigeninteractive/eigen-server";

const config: Config = {
  title: "EigenInteractive",
  tagline: "Build games, not boilerplate",
  // The .ico is only the legacy fallback; `headTags` below links the SVG that
  // actually adapts to the reader's colour scheme. Every brand asset lives in
  // static/brand/ and is generated by `pnpm run generate-brand`.
  favicon: "brand/favicon.ico",

  headTags: [
    // A browser cannot choose between a light and a dark icon *file*: <link>
    // has no prefers-color-scheme selector, so this one SVG restyles itself.
    // Browsers that understand it prefer it over the .ico above.
    {
      tagName: "link",
      attributes: {
        rel: "icon",
        type: "image/svg+xml",
        href: "/brand/favicon.svg",
      },
    },
    {
      tagName: "link",
      attributes: {
        rel: "apple-touch-icon",
        href: "/brand/apple-touch-icon-180.png",
      },
    },
    // static/site.webmanifest was previously never linked from any page, so
    // the manifest, and the installable-PWA behaviour it describes, was dead
    // weight. This is what activates it.
    {
      tagName: "link",
      attributes: { rel: "manifest", href: "/site.webmanifest" },
    },
    // Tints mobile browser chrome. The manifest's `theme_color` only applies
    // once installed, so a browsing visitor never sees it without these.
    //
    // Declared here rather than in `themeConfig.metadata` on purpose: two
    // tags share the name `theme-color` and differ only by `media`, and
    // react-helmet de-duplicates meta by name and would keep just one of
    // them. `headTags` is emitted verbatim, so both survive.
    {
      tagName: "meta",
      attributes: {
        name: "theme-color",
        media: "(prefers-color-scheme: light)",
        content: "#F4F1EA",
      },
    },
    {
      tagName: "meta",
      attributes: {
        name: "theme-color",
        media: "(prefers-color-scheme: dark)",
        content: "#1B1E24",
      },
    },
    // Structured data. Search engines and LLM crawlers read this to work out
    // *what kind of thing* this site is, which no amount of prose in a meta
    // description tells them. Three nodes in one graph, cross-referenced by
    // @id: the publisher, the site itself, and the engine as a piece of
    // software. `applicationCategory: DeveloperApplication` plus
    // `SoftwareSourceCode` is what distinguishes an engine you build on from a
    // game you play, and that distinction is the whole ranking problem here.
    //
    // Emitted on every page, which is correct for site-level entities: the
    // graph describes the site, not the page. Anything page-level (a
    // BreadcrumbList, a TechArticle) would have to be emitted per page
    // instead, and Docusaurus already gives search engines the breadcrumb
    // trail through the sidebar markup.
    {
      tagName: "script",
      attributes: { type: "application/ld+json" },
      innerHTML: JSON.stringify({
        "@context": "https://schema.org",
        "@graph": [
          {
            "@type": "Organization",
            "@id": "https://eigeninteractive.com/#organization",
            name: "EigenInteractive",
            url: "https://eigeninteractive.com",
            logo: "https://eigeninteractive.com/brand/eigen-lockup-360.png",
            sameAs: ["https://github.com/eigeninteractive"],
          },
          {
            "@type": "WebSite",
            "@id": "https://eigeninteractive.com/#website",
            name: "EigenInteractive",
            url: "https://eigeninteractive.com",
            publisher: { "@id": "https://eigeninteractive.com/#organization" },
            inLanguage: "en",
          },
          {
            "@type": ["SoftwareApplication", "SoftwareSourceCode"],
            "@id": "https://eigeninteractive.com/#engine",
            name: "EigenInteractive",
            applicationCategory: "DeveloperApplication",
            operatingSystem: "Android, Web",
            programmingLanguage: ["TypeScript", "Dart"],
            runtimePlatform: ["Cloudflare Workers", "Cloudflare Durable Objects", "Flutter"],
            codeRepository: GITHUB,
            license: "https://opensource.org/licenses/MIT",
            isAccessibleForFree: true,
            url: "https://eigeninteractive.com",
            publisher: { "@id": "https://eigeninteractive.com/#organization" },
            description:
              "An open-source, server-authoritative engine for turn-based multiplayer games: board games, card games and abstract strategy. A game ships as one Cloudflare Worker, using Durable Objects for each live session, plus one Flutter app for Android and the web. The implementor writes the rules; the engine owns accounts, lobby, sockets, turn clocks, ratings, push and the store release.",
            offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
          },
        ],
      }),
    },
  ],

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  //
  // `v4: true` turns on every v4 flag, and one of them,
  // `mdx1CompatDisabledByDefault`, switches off the whole `markdown.mdx1Compat`
  // block. Two consequences bite when authoring, and neither is a build error:
  //
  //   · Admonition titles must be bracketed: `:::tip[Title]`, not `:::tip Title`.
  //     The unbracketed form is not a directive at all without the shim, so the
  //     block silently renders as a literal paragraph. `pnpm check-admonitions`
  //     guards this.
  //   · HTML comments are gone. Use `{/* ... */}`, which is what the generated
  //     region markers in docs/reference/compatibility.md are written with.
  //
  // (`{#heading-id}` still needs escaping as `\{#heading-id}`; that one does
  // fail the build, so it catches itself.)
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // The production URL. It drives canonical tags and the generated sitemap, so it
  // must be the real host.
  url: "https://eigeninteractive.com",
  baseUrl: "/",
  // Emit URLs without a trailing slash, matching the worker-served game pages.
  trailingSlash: false,

  organizationName: "eigeninteractive",
  projectName: "eigen-web",

  onBrokenLinks: "throw",

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
          // Every doc page is authored here, since this site is the source of
          // truth for the documentation, so "edit this page" points at it.
          editUrl: "https://github.com/eigeninteractive/eigen-web/tree/main/",
          // The OpenAPI theme swizzles the doc item to render request/response
          // panels. Non-API pages render exactly as before.
          docItemComponent: "@theme/ApiItem",

          // Versioned on the engine's RELEASE LINE: the constraint a reader
          // writes to install what these pages describe. Pre-1.0 that line is
          // the minor: `^0.2.0` resolves to `>=0.2.0 <0.3.0`, so 0.2.x is one
          // line and 0.3.0 starts the next. Once the engine reaches 1.0.0 this
          // becomes "1.x" and tracks the major.
          //
          // The release line rather than the wire contract, and the difference
          // is not academic: 0.2.0 moved the engine's line without touching
          // openapi.json at all (it was a TypeScript barrel cleanup) and
          // these pages document the TypeScript half as much as the Dart half.
          // `eigen_flutter` is NOT an axis here; it moves on its own clock and
          // declares its own pairing. See /docs/reference/compatibility.
          //
          // `pnpm check-docs-version` asserts this label against `info.version`
          // in the committed api/openapi.json, which is the engine's own stamp.
          // So the sync pull request that lands a new engine line FAILS rather
          // than silently relabelling the site. Crossing a line is a decision,
          // cut the old one or relabel in place, and that check is what forces
          // someone to make it.
          //
          // No version is CUT yet, and that is deliberate twice over.
          // Docusaurus' own guidance is that versioning "will just increase
          // your build time, and introduce complexity"; a cut snapshots all of
          // `docs/` into `versioned_docs/`, and the bulk of this site is the
          // generated TypeDoc and HTTP reference, so a cut roughly doubles both
          // the build and the local search index. There has also been nothing
          // to freeze: the site's first public deploy already served 0.2.x, so
          // no 0.1.x page was ever reachable to keep working.
          //
          // 0.2.x was RELABELLED rather than cut, which is worth recording
          // because it is the first crossing where a cut was arguable: the line
          // was published, and `eigen_flutter` 0.3.x is on npm pinning it. It
          // was still the right answer. The engine has no adopters to strand,
          // the session-snapshot release edited the game object's init migration
          // in place, so a 0.2.x game's local state does not survive the upgrade
          // anyway, and a frozen 0.2.x line would have gone on describing a wire
          // no engine can still speak. That is worse than absent.
          //
          // 0.3.x was relabelled too, and it is the least arguable crossing yet
          // despite being the most published. That line's paged reads were
          // broken: a first-page request arrived with an empty `cursor`, which
          // coerced to `0`, so every lobby and history list answered `200 []`.
          // 0.4.0 is the fix, and it is a wire change, opaque cursors and
          // `nextCursor`. Freezing 0.3.x would have published a permanent,
          // searchable description of a protocol whose lists are always empty,
          // next to the one that works. Nobody wants to read that page.
          //
          // Naming the current version costs no URLs: Docusaurus serves
          // `lastVersion` at the base path, so these pages stay at /docs/*.
          // Once the engine has adopters who cannot follow a line break, run
          //
          //   pnpm docusaurus docs:version 0.4.x
          //
          // and 0.4.x freezes into `versioned_docs/version-0.4.x` at
          // /docs/0.4.x/* while `docs/` becomes the new line at /docs/*. The
          // generated reference freezes with it, which is exactly right:
          // `sync-api` keeps writing to `docs/`, so no part of that pipeline
          // has to learn about versions. CONTRIBUTING.md has the procedure.
          lastVersion: "current",
          versions: {
            current: {
              // Asserted against api/openapi.json; see check-docs-version.
              label: "0.4.x",
            },
          },
        },
        blog: {
          showReadingTime: true,
          blogTitle: "Changelog",
          blogDescription: "Releases and notable changes to the EigenInteractive engine.",
          feedOptions: {
            type: ["rss", "atom"],
            xslt: true,
          },
          // Useful options to enforce blogging best practices
          onInlineTags: "warn",
          onInlineAuthors: "warn",
          onUntruncatedBlogPosts: "warn",
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
        // `/search` is the local search plugin's results page. It has no
        // content of its own, and Google's own guidance is to keep internal
        // search results out of the index, so it does not belong in the
        // sitemap either. Everything else here is a real page.
        sitemap: {
          ignorePatterns: ["/search"],
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    // Required by docusaurus-theme-openapi-docs, which ships Sass.
    "docusaurus-plugin-sass",

    // Turns the engine's emitted spec into MDX. This does not run during
    // `build`; it runs on demand via `pnpm sync-api`, and its output is
    // committed, so the site builds without the sibling checkout.
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "openapi",
        docsPluginId: "classic",
        config: {
          engine: {
            specPath: "api/openapi.json",
            outputDir: "docs/reference/http-api",
            downloadUrl: "/openapi.json",
            sidebarOptions: {
              groupPathsBy: "tag",
              categoryLinkSource: "tag",
            },
          },
        },
      },
    ],

    // Agent-facing output: /llms.txt (the index), /llms-full.txt (everything
    // in one file) and a .md twin of every page.
    //
    // The generated HTTP reference is deliberately excluded. Those pages are
    // <ApiTabs>/<SchemaItem> component trees, so their markdown source is
    // JSX scaffolding rather than prose, and an agent is better served by
    // the real spec at /openapi.json, which llms.txt links to instead.
    [
      "docusaurus-plugin-llms",
      {
        title: "EigenInteractive",
        description: "An open-source, server-authoritative engine for turn-based multiplayer games. A game ships as a single Cloudflare Worker that owns its own domain, database and players, plus a Flutter app for Android and the web. The implementor writes the rules; the engine owns everything else.",
        generateLLMsTxt: true,
        generateLLMsFullTxt: true,
        generateMarkdownFiles: true,
        excludeImports: true,
        removeDuplicateHeadings: true,
        ignoreFiles: ["reference/http-api/**"],
        pathTransformation: {
          ignorePaths: ["docs"],
        },
        // Reading order for llms-full.txt: orient, then build, then the
        // details. Matches the sidebar.
        includeOrder: ["intro.mdx", "getting-started/**", "build-a-game/**", "ship-it/**", "how-it-works/**", "reference/**"],
        includeUnmatchedLast: true,
      },
    ],
  ],

  themes: [
    "docusaurus-theme-openapi-docs",
    [
      // Local search: no Algolia account, no third-party request from the
      // browser, and it indexes at build time. Keeps the site free of
      // external dependencies, which is also why analytics is Cloudflare's
      // cookieless beacon rather than gtag.
      "@easyops-cn/docusaurus-search-local",
      {
        hashed: true,
        indexBlog: true,
        docsRouteBasePath: "/docs",
        blogRouteBasePath: "/blog",
        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
      },
    ],
  ],

  themeConfig: {
    // Default social/OG card (1200x630), emitted as og:image + twitter:image.
    image: "brand/og-card.png",
    // Docusaurus emits og:image/twitter:image/og:title/og:description/og:url
    // and the canonical link on its own. It does NOT emit any of the five
    // below, so they are declared here.
    //
    // The dimensions are safe to state globally only because no page
    // overrides `image` in its front matter, so every page shares the one
    // 1200x630 card. A page-level override would need its own width/height
    // beside it, since react-helmet would replace og:image but leave these.
    metadata: [
      // The site-wide fallback: what any page without its own front-matter
      // `description` gets, and what a link to the bare domain unfurls as. It
      // carries the terms someone would actually search: open source,
      // turn-based multiplayer, Cloudflare Workers, Durable Objects, Flutter,
      // Android, because "engine for turn-based multiplayer games" alone
      // competes with every board-game app ever listed.
      {
        name: "description",
        content: "Open-source engine for turn-based multiplayer games: board, card and abstract strategy. One Cloudflare Worker with Durable Objects, one Flutter app for Android and the web.",
      },
      { property: "og:type", content: "website" },
      { property: "og:site_name", content: "EigenInteractive" },
      { property: "og:image:width", content: "1200" },
      { property: "og:image:height", content: "630" },
      {
        property: "og:image:alt",
        content: "EigenInteractive, the open-source engine for turn-based multiplayer games",
      },
    ],
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "EigenInteractive",
      logo: {
        alt: "EigenInteractive",
        src: "brand/eigen-mark.svg",
        // The mark is two-colour and must not sit on a mid-tone; the reversed
        // variant is what carries it against the dark navbar.
        srcDark: "brand/eigen-mark-dark.svg",
      },
      items: [
        {
          type: "docSidebar",
          sidebarId: "docsSidebar",
          position: "left",
          label: "Docs",
        },
        {
          type: "docSidebar",
          sidebarId: "referenceSidebar",
          position: "left",
          label: "Reference",
        },
        { to: "/showcase", label: "Showcase", position: "left" },
        { to: "/blog", label: "Changelog", position: "left" },
        // Renders as "0.4.x", the label from `versions.current` above. With one
        // version live it exists to answer "which engine is this describing",
        // and it becomes an ordinary switcher once a version is cut.
        //
        // Nothing is pinned in via `dropdownItemsAfter`, and the compatibility
        // table specifically must not be. Each version entry links to *the doc
        // you are currently reading* in that version, so on a versioned page the
        // entry is a self-link; adding a versioned doc to the dropdown makes the
        // two collide on that doc's own page, where both render with
        // `dropdown__link--active` pointing at the same href. Docusaurus' own
        // example pins `/versions`, a page outside `/docs` that no version owns,
        // which is the case this option is for. Compatibility lives in
        // `referenceSidebar` and is reachable there.
        //
        // `dropdownActiveClassDisabled` because each version entry links to the
        // doc you are currently reading, which makes it a self-link on every
        // docs page and so permanently "active". Highlighting it says nothing:
        // with one version there is no other state it could be in. Docusaurus'
        // own example sets this for the same reason.
        {
          type: "docsVersionDropdown",
          position: "right",
          dropdownActiveClassDisabled: true,
        },
        {
          href: GITHUB,
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            { label: "Introduction", to: "/docs/intro" },
            { label: "Quickstart", to: "/docs/getting-started/quickstart" },
            { label: "Build a game", to: "/docs/build-a-game/the-contract" },
            { label: "Ship it", to: "/docs/ship-it/deploy-the-worker" },
          ],
        },
        {
          title: "Reference",
          items: [
            // This slug is the kebab-cased `info.title` of the engine's
            // openapi.json. `docusaurus-plugin-openapi-docs` derives the info
            // page's id from it and offers no way to pin it. So renaming the
            // spec's title moves this page, and every hand-written link to it
            // breaks on the next `sync-api`. Grep for the old slug when that
            // happens; the generated `.api.mdx` front matter fixes itself.
            { label: "HTTP API", to: "/docs/reference/http-api/eigeninteractive-engine-api" },
            { label: "TypeScript API", to: "/docs/reference/typescript" },
            { label: "Dart API", href: "https://pub.dev/documentation/eigen_flutter/latest/" },
            // `pathname://` opts out of the SPA router *and* the broken-link
            // check; these are static/post-build artifacts, not routes.
            { label: "OpenAPI spec", to: "pathname:///openapi.json" },
            { label: "llms.txt", to: "pathname:///llms.txt" },
          ],
        },
        {
          title: "Project",
          items: [
            { label: "GitHub", href: GITHUB },
            { label: "Changelog", to: "/blog" },
            { label: "License (MIT)", href: `${GITHUB}/blob/main/LICENSE` },
          ],
        },
        {
          title: "Legal",
          items: [{ label: "Privacy Policy", to: "/privacy" }],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} EigenInteractive. MIT-licensed. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ["bash", "json", "dart", "yaml", "sql"],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
